version: '3.8'

services:
  backend:
    image: image-similarity-backend:latest
    ports:
      - "8000:8000"
    environment:
      - QDRANT_HOST=qdrant
      - REDIS_HOST=redis
      - CELERY_BROKER_URL=amqp://admin:admin@rabbitmq:5672//
    depends_on:
      - qdrant
      - redis
      - rabbitmq
    networks:
      - app-network

  celery-worker:
    image: image-similarity-backend:latest
    command: celery -A app.core.celery_app worker --loglevel=info
    environment:
      - QDRANT_HOST=qdrant
      - REDIS_HOST=redis
      - CELERY_BROKER_URL=amqp://admin:admin@rabbitmq:5672//
    depends_on:
      - backend
      - rabbitmq
    networks:
      - app-network

  qdrant:
    image: qdrant/qdrant:v1.14.0
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  qdrant_data:
  redis_data:
  rabbitmq_data:
