version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:v1.14.0
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      QDRANT__LOG_LEVEL: INFO
    restart: unless-stopped
    healthcheck:
      test: "curl -f http://localhost:6333/health"
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: "redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru"
    restart: unless-stopped
    healthcheck:
      test: "redis-cli ping"
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  qdrant_data:
  redis_data:
