apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: image-similarity
spec:
  template:
    spec:
      containers:
      - name: backend
        resources:
          requests:
            memory: "4Gi"
            cpu: "2000m"
          limits:
            memory: "8Gi"
            cpu: "4000m"
