apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: image-similarity-prod

bases:
  - ../../base

patchesStrategicMerge:
  - deployment-patch.yaml

configMapGenerator:
  - name: backend-config
    behavior: merge
    literals:
      - DEBUG=false
      - LOG_LEVEL=WARNING

replicas:
  - name: backend
    count: 5
  - name: celery-worker
    count: 3
