apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
  namespace: image-similarity
spec:
  replicas: 2
  selector:
    matchLabels:
      app: celery-worker
  template:
    metadata:
      labels:
        app: celery-worker
    spec:
      containers:
      - name: celery-worker
        image: image-similarity-backend:latest
        command: ["celery", "-A", "app.core.celery_app", "worker", "--loglevel=info"]
        envFrom:
        - configMapRef:
            name: backend-config
        - secretRef:
            name: backend-secret
        env:
        - name: CELERY_BROKER_URL
          value: "amqp://admin:$(RABBITMQ_PASSWORD)@rabbitmq-service:5672//"
        - name: REDIS_HOST
          value: "redis-service"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
