apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: image-similarity
data:
  APP_NAME: "Image Similarity Engine"
  APP_VERSION: "0.1.0"
  DEBUG: "false"
  LOG_LEVEL: "INFO"
  API_HOST: "0.0.0.0"
  API_PORT: "8000"
  API_PREFIX: "/api/v1"
  MODEL_NAME: "openai/clip-vit-base-patch32"
  MODEL_CACHE_DIR: "/models"
  BATCH_SIZE: "32"
  DEVICE: "auto"
  QDRANT_COLLECTION_NAME: "image_features"
  SEARCH_TIMEOUT: "30"
  CACHE_TTL: "3600"
  MAX_IMAGE_SIZE: "10485760"
